/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResumoGeralRouteImport } from './routes/resumo-geral'
import { Route as MercadoRouteImport } from './routes/mercado'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'

const ResumoGeralRoute = ResumoGeralRouteImport.update({
  id: '/resumo-geral',
  path: '/resumo-geral',
  getParentRoute: () => rootRouteImport,
} as any)
const MercadoRoute = MercadoRouteImport.update({
  id: '/mercado',
  path: '/mercado',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mercado': typeof MercadoRoute
  '/resumo-geral': typeof ResumoGeralRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mercado': typeof MercadoRoute
  '/resumo-geral': typeof ResumoGeralRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mercado': typeof MercadoRoute
  '/resumo-geral': typeof ResumoGeralRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/mercado' | '/resumo-geral'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/mercado' | '/resumo-geral'
  id: '__root__' | '/' | '/login' | '/mercado' | '/resumo-geral'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MercadoRoute: typeof MercadoRoute
  ResumoGeralRoute: typeof ResumoGeralRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resumo-geral': {
      id: '/resumo-geral'
      path: '/resumo-geral'
      fullPath: '/resumo-geral'
      preLoaderRoute: typeof ResumoGeralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mercado': {
      id: '/mercado'
      path: '/mercado'
      fullPath: '/mercado'
      preLoaderRoute: typeof MercadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MercadoRoute: MercadoRoute,
  ResumoGeralRoute: ResumoGeralRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
